// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXI9YW8HuEkn_KVUrU-LC5m1HwN1QEgO8',
    appId: '1:737204936841:web:7f455db2a0301887bba658',
    messagingSenderId: '737204936841',
    projectId: 'jsom-c23a1',
    authDomain: 'jsom-c23a1.firebaseapp.com',
    storageBucket: 'jsom-c23a1.appspot.com',
    measurementId: 'G-5KM5VJC4Q4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGtelCTfPhpKoMPoOt6HcfaFt8xUcua4c',
    appId: '1:737204936841:android:f2e099bdf71c571abba658',
    messagingSenderId: '737204936841',
    projectId: 'jsom-c23a1',
    storageBucket: 'jsom-c23a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq57C9p9ew15_TSUJOVwtmQiINciXK91Y',
    appId: '1:737204936841:ios:83a0640472aaef9dbba658',
    messagingSenderId: '737204936841',
    projectId: 'jsom-c23a1',
    storageBucket: 'jsom-c23a1.appspot.com',
    iosBundleId: 'com.example.josm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq57C9p9ew15_TSUJOVwtmQiINciXK91Y',
    appId: '1:737204936841:ios:d12a2f01aebfeffabba658',
    messagingSenderId: '737204936841',
    projectId: 'jsom-c23a1',
    storageBucket: 'jsom-c23a1.appspot.com',
    iosBundleId: 'com.example.josm.RunnerTests',
  );
}
